import json
import re

dictionary = {
    "%@ • %@": "%1$@ • %2$@",
    "%@ için kişiselleştirilmiş\nuyku profili oluşturuldu": "Personalized sleep profile\ncreated for %@",
    "%@ nasıl? %@ bugün tam %@.": "How is %@? %@ is exactly %@ today.",
    "%@'in Uyku Koçu": "%@'s Sleep Coach",
    "%@sa": "%@h",
    "•": "•",
    "📅 %@": "📅 %@",
    "88": "88",
    "Abonelik, seçilen plana göre otomatik olarak yenilenir. İstediğiniz zaman Ayarlar > Apple Kimliği > Abonelikler üzerinden iptal edebilirsiniz. İptal, mevcut dönemin sonunda geçerli olur.": "The subscription automatically renews depending on the selected plan. You can cancel anytime via Settings > Apple ID > Subscriptions. Cancellation is effective at the end of the current period.",
    "Adını yazın...": "Type name...",
    "AI Koç Analizi": "AI Coach Analysis",
    "Akıllı Uyku Asistanı": "Smart Sleep Assistant",
    "Anne Karnı + Beyaz Gürültü": "Womb + White Noise",
    "Anne Karnı Huzuru": "Womb Harmony",
    "Arka Planda Çalmaya Devam": "Continue Playing in Background",
    "Ayarlar": "Settings",
    "Aylık Plan": "Monthly Plan",
    "Ayrılık Kaygısı Dönemi: Uykuya dalışta yanınızda olmak isteyebilir. Rutinleri koruyun.": "Separation Anxiety Period: May want you nearby when falling asleep. Keep routines.",
    "Başarı Puanı": "Success Score",
    "Başlayalım": "Let's Start",
    "Bebeğin Adı": "Baby's Name",
    "Bebeğinizi Tanıyalım": "Let's Get to Know Your Baby",
    "Bebeğinizin adı": "Your baby's name",
    "Bebeğinizin gelişimine uyum sağlayan,\nkişiselleştirilmiş uyku deneyimi": "Personalized sleep experience\nadapted to your baby's development",
    "Bebek\nUyandı": "Baby\nWoke Up",
    "Bebek\nUyudu": "Baby\nFell Asleep",
    "Beyaz Gürültü": "White Noise",
    "Bildirimler": "Notifications",
    "Birkaç uyku oturumu kaydettikten sonra\ngrafikler burada görünecek": "Charts will appear here\nafter recording a few sleep sessions",
    "Bu işlem geri alınamaz. Tüm bebek profili, uyku verileri ve ayarlar silinecektir.": "This action cannot be undone. All baby profile, sleep data and settings will be deleted.",
    "Bu kategoride henüz ses yok": "No sounds in this category yet",
    "Bugün hedef: %@ saat uyku": "Today's goal: %@ hours of sleep",
    "Derin Analizler": "Deep Analytics",
    "Destek & Geliştirici": "Support & Developer",
    "Destek & Geri Bildirim": "Support & Feedback",
    "Destek: bunyaminkahraman027@icloud.com": "Support: bunyaminkahraman027@icloud.com",
    "Devam": "Continue",
    "Devam Et": "Continue",
    "Developer: Kahramandev": "Developer: Kahramandev",
    "Dil Seçimi": "Language Selection",
    "Doğa Sesleri": "Nature Sounds",
    "Doğum tarihi": "Date of Birth",
    "Doğum Tarihi": "Date of Birth",
    "Email: bunyaminkahraman027@icloud.com": "Email: bunyaminkahraman027@icloud.com",
    "En Etkili Kombinasyon": "Most Effective Combination",
    "En fazla 2 zorluk seçin.\nSize özel öneriler sunalım.": "Select up to 2 difficulties.\nWe'll provide tailored recommendations.",
    "English": "English",
    "Gece Uykusuna Dön": "Return to Night Sleep",
    "Gizlilik Politikası": "Privacy Policy",
    "Gündüz uykularındaki kesintiler son 3 gündür artış eğiliminde. 4. ay uyku gerilemesi dönemi başlamış olabilir. Rutinleri şaşmamaya ve uyanık kalma sürelerini 1.5 saatte tutmaya özen gösterin.": "Daytime sleep interruptions have been increasing for the last 3 days. The 4-month sleep regression might have started. Stick to routines and aim to keep awake times around 1.5 hours.",
    "Haftalık Rapor": "Weekly Report",
    "Haftalık Uyku": "Weekly Sleep",
    "Hedef: %@ Saat": "Goal: %@ Hours",
    "Henüz yeterli veri yok": "Not enough data yet",
    "Hikayede Paylaş": "Share to Story",
    "Hızlı Uyu": "Fall Asleep Fast",
    "Kalp Atışı": "Heartbeat",
    "Kaydet": "Save",
    "Keşfetmeye Başla": "Start Exploring",
    "Kesintisiz Uyku": "Uninterrupted Sleep",
    "Kişiselleştirilmiş uyku deneyimi için\nbirkaç bilgiye ihtiyacımız var": "We need some information\nfor a personalized sleep experience",
    "Kullanım Şartları (EULA)": "Terms of Use (EULA)",
    "Milestone Bildirimleri": "Milestone Notifications",
    "Mükemmel! Bebeğinizin uyku derinliği artıyor.": "Excellent! Your baby's sleep depth is increasing.",
    "NinniAI": "NinniAI",
    "Normal moda geç": "Switch to normal mode",
    "Okyanus Sesi": "Ocean Sound",
    "Ortam Sesleri": "Ambient Sounds",
    "Premium'a Geç": "Upgrade to Premium",
    "Pro": "Pro",
    "PRO": "PRO",
    "Profesyonel Uyku Danışmanı.": "Professional Sleep Consultant.",
    "puan": "score",
    "Sakin seslerle tekrar uykuya dal": "Fall back asleep with calming sounds",
    "Sistem Dili": "System Language",
    "SİSTEM ÖNERİSİ": "SYSTEM SUGGESTION",
    "Son 7 gün": "Last 7 days",
    "Süre bittiğinde sesler yavaşça kapanır": "Sounds gradually fade out when the timer ends",
    "Sürüm %@ (Build %@)": "Version %1$@ (Build %2$@)",
    "Toplam Uyku": "Total Sleep",
    "Tüm Verileri Sil": "Delete All Data",
    "Türkçe": "Turkish",
    "Uygulama Dili": "App Language",
    "Uyku Hatırlatma": "Sleep Reminder",
    "Uyku Kalite Skoru": "Sleep Quality Score",
    "UYKU KOÇU (PRO)": "SLEEP COACH (PRO)",
    "Uyku Zorlukları": "Sleep Challenges",
    "Website: bunyamin027.github.io/Legal": "Website: bunyamin027.github.io/Legal",
    "Yasal Bilgiler & Lisanslar": "Legal Information & Licenses",
    "Yıllık Plan": "Yearly Plan",
    "Zamanlayıcı": "Timer",
    "Zamanlayıcı Kapalı": "Timer Off",
    "Zamanlayıcıyı İptal Et": "Cancel Timer",
    "Kozmik İyileşme": "Cosmic Healing",
    "174 Hz frekansında derin rahatlama titreşimi": "Deep relaxation vibration at 174 Hz",
    "Topraklama Frekansı": "Grounding Frequency",
    "Güvenlik ve huzur hissi veren derin tonlar": "Deep tones giving a sense of security and peace",
    "Yenilenme Dalgaları": "Waves of Renewal",
    "Tazeleyici ve arındırıcı ses frekansları": "Refreshing and purifying sound frequencies",
    "Doğanın Frekansı": "Nature's Frequency",
    "Evrenin doğal titreşimiyle uyum": "Harmony with the universe's natural vibration",
    "Sonsuz Şefkat Tonu": "Tone of Infinite Compassion",
    "Kalp merkezli sakinleştirici frekans": "Heart-centered calming frequency",
    "Arınma Seremonisi": "Purification Ceremony",
    "Çoklu frekanslarla derinlemesine huzur": "Deep peace with multiple frequencies",
    "Yıldız Işığı Frekansı": "Starlight Frequency",
    "Yüksek titreşimli kozmik uyum dalgaları": "High-vibration cosmic harmony waves",
    "Kutsal Üçlü Harmoni": "Sacred Trinity Harmony",
    "Üç iyileştirici frekansın büyülü buluşması": "Magical meeting of three healing frequencies",
    "Kadife Beyaz Gürültü": "Velvet White Noise",
    "Binaural beatlerle zenginleştirilmiş yumuşak örtü": "Soft cover enriched with binaural beats",
    "Gece Yağmuru Fısıltısı": "Night Rain Whisper",
    "Karanlıkta huzurla yağan damlalar": "Drops falling peacefully in the dark",
    "Gümüş Yağmur Damlaları": "Silver Raindrops",
    "Uzak gök gürültüsü ve piyanonun dansı": "Dance of distant thunder and piano",
    "Uykulu Yağmur": "Sleepy Rain",
    "Uyku getiren hafif yağmur melodisi": "Sleep-inducing light rain melody",
    "Derin Okyanus": "Deep Ocean",
    "Sonsuz maviliğin derin ve ritmik dalgaları": "Deep and rhythmic waves of the endless blue",
    "Orman Ninnisi": "Forest Lullaby",
    "Ağaçların arasından süzülen doğa melodisi": "Nature melody filtering through the trees",
    "Çöl Gecesi Sessizliği": "Desert Night Silence",
    "Yıldızlı çölün büyüleyici atmosferi": "Enchanting atmosphere of the starry desert",
    "Yıldız Tozu Ninnisi": "Stardust Lullaby",
    "Gökyüzünden süzülen büyülü bir melodi": "Magical melody drifting from the sky",
    "Ay Işığı Piyanisi": "Moonlight Piano",
    "Dolunayın altında dans eden piyano notaları": "Piano notes dancing under the full moon",
    "Tatlı Rüyalar Kutusu": "Sweet Dreams Box",
    "Müzik kutusundan dökülen pamuk şeker melodiler": "Cotton candy melodies pouring from the music box",
    "Beşik Şarkısı": "Cradle Song",
    "Nesillerden süzülen sıcacık beşik melodisi": "Warm cradle melody passed down through generations",
    "Bulutların Üzerinde": "Above the Clouds",
    "Pamuk bulutlarda süzülen hafif ninni": "Light lullaby floating on cotton clouds",
    "Arp Masalı": "Harp Tale",
    "İrlanda arpının büyüleyici huzur ezgisi": "Enchanting peaceful melody of the Irish harp",
    "Sessiz Gece Melodisi": "Silent Night Melody",
    "Gecenin derinliğinden yükselen uyku ezgisi": "Sleep melody rising from the depths of the night",
    "Uyku Perisi": "Sleep Fairy",
    "Gözleri tatlı tatlı kapatan sihirli melodi": "Magical melody that sweetly closes the eyes",
    "Rüya Bahçesi": "Dream Garden",
    "Çiçeklerin arasında dans eden notalar": "Notes dancing among the flowers",
    "Bulut Beşiği": "Cloud Cradle",
    "Rüyalar diyarına taşıyan yumuşak ezgi": "Soft melody carrying to the land of dreams",
    "Kristal Müzik Kutusu": "Crystal Music Box",
    "Antik müzik kutusunun büyülü tınısı": "Magical chime of the antique music box",
    "Ninni Esintisi": "Lullaby Breeze",
    "Hafif bir esinti gibi saran uyku melodisi": "Sleep melody wrapping like a light breeze",
    "Sonsuz Beşik Salınımı": "Endless Cradle Swing",
    "Hiç bitmeyen, nazikçe sallanan ninni döngüsü": "Never-ending, gently swaying lullaby loop",
    "Kadife Uyku": "Velvet Sleep",
    "Kadife gibi sarmalayan derin uyku melodisi": "Deep sleep melody wrapping like velvet",
    "Anne Şefkati Ritimleri": "Mother's Affection Rhythms",
    "Annenin kalbinden yayılan güven dolu ritim": "Confident rhythm spreading from the mother's heart",
    "Güvenli Kucak": "Safe Embrace",
    "Bebeği saran koruyucu kalp atışı": "Protective heartbeat embracing the baby",
    "Rahmin sıcak ve korunaklı sessizliği": "Warm and sheltered silence of the womb",
    "Huzur Tapınağı": "Temple of Peace",
    "Derin meditasyonun sakin atmosferi": "Calm atmosphere of deep meditation",
    "Sessizlik Vadisi": "Valley of Silence",
    "Dağların arasındaki sonsuz huzur": "Endless peace among the mountains",
    "Mavi Düşler": "Blue Dreams",
    "Gökyüzünün mavisinde süzülen dinginlik": "Serenity drifting in the blue of the sky",
    "İç Huzur Yolculuğu": "Inner Peace Journey",
    "Ruhun derinliklerine yapılan sakin yolculuk": "Calm journey to the depths of the soul",
    "Sabah Çiği Meditasyonu": "Morning Dew Meditation",
    "Şafakta parlayan çiy damlalarının sessizliği": "Silence of dewdrops shining at dawn",
    "Zen Bahçesi": "Zen Garden",
    "Taş bahçesinin derin ve arındırıcı huzuru": "Deep and purifying peace of the stone garden",
    "Sakin Kütüphane": "Calm Library",
    "Kitaplar arasında süzülen dingin melodi": "Serene melody floating among books",
    "Kadife Sessizlik": "Velvet Silence",
    "Her şeyin durduğu derin bir an": "A deep moment where everything stops",
    "Barış Duası": "Prayer for Peace",
    "Huzur dolu piyanonun duygusal ezgisi": "Emotional melody of a peaceful piano",
    "Altın Gitar Huzuru": "Golden Guitar Peace",
    "Akustik gitarın sıcacık dokunuşu": "Warm touch of the acoustic guitar",
    "Sıcak Şömine Piyanisi": "Warm Fireplace Piano",
    "Şömine başında çalınan huzurlu piyano": "Peaceful piano played by the fireplace",
    "Uzay İstasyonu": "Space Station",
    "Yörüngede süzülen kozmik ortam sesleri": "Cosmic ambient sounds floating in orbit",
    "Gece Yolculuğu": "Night Journey",
    "Yıldızların arasında uyku yolculuğu": "Sleep journey among the stars",
    "Yağmurun Öpücüğü": "Kiss of the Rain",
    "Yağmur damlalarıyla dans eden piyano": "Piano dancing with raindrops",
    "Tatlı Rüzgar Dansı": "Sweet Wind Dance",
    "Neşeli ve hafif sallanan uyku ritmi": "Cheerful and gently swaying sleep rhythm",
    "Melek Gülümsemesi": "Angel Smile",
    "Bebeğin yüzündeki gülümsemeyi getiren melodi": "Melody bringing a smile to the baby's face",
    "Küçük Sevinçler": "Little Joys",
    "Minicik kalplerin neşe dolu anları": "Joyful moments of tiny hearts",
    "Pamuk Uyku": "Cotton Sleep",
    "Bulutlar kadar yumuşak uyku atmosferi": "Sleep atmosphere as soft as clouds",
    "Güneşli Sabah": "Sunny Morning",
    "Neşeli bir güne uyanışın melodisi": "Melody of waking up to a cheerful day",
    "Rüya Atölyesi": "Dream Workshop",
    "Hayal gücüyle dolu renkli bir dünya": "A colorful world full of imagination",
    "Peri Masalı": "Fairy Tale",
    "Masalların dünyasına açılan sihirli kapı": "Magical door opening to the world of fairy tales",
    "Oyun Kutusu": "Toy Box",
    "Neşeli ve keyifli çocukluk anıları": "Cheerful and pleasant childhood memories",
    "Gökkuşağı Yolculuğu": "Rainbow Journey",
    "Rengarenk bir düşler diyarına yolculuk": "Journey to a colorful land of dreams",
    "Küçük Kaşif": "Little Explorer",
    "Meraklı gözlerle keşfedilen yeni dünya": "A new world explored with curious eyes",
    "Yıldız Parkı": "Star Park",
    "Yıldızların altında oynanan oyunlar": "Games played under the stars",
    "Player": "Player",
    "Ninniler": "Lullabies",
    "Abonelikleri Yönet": "Manage Subscriptions",
    "Aylık sadece ₺41,67": "Only ₺41,67 monthly",
    "Her ay yenilenir": "Renews every month",
    "Hemen Başla": "Start Now",
    "Seç": "Select",
    "%40 TASARRUF": "40% SAVINGS"
}

file_path = 'NinniAI/Localizable.xcstrings'
import os
if not os.path.exists(file_path):
    data = {
        "sourceLanguage": "tr",
        "strings": {},
        "version": "1.0"
    }
else:
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

# Ensure all items in dictionary exist in strings
for key, value in dictionary.items():
    if key not in data['strings']:
        data['strings'][key] = {}
        
    if 'localizations' not in data['strings'][key]:
        data['strings'][key]['localizations'] = {}
        
    data['strings'][key]['localizations']['en'] = {
        'stringUnit': {
            'state': 'translated',
            'value': value
        }
    }

# Ensure existing keys also have translations if possible
for key, val_obj in data['strings'].items():
    if key in dictionary:
        if 'localizations' not in val_obj:
            val_obj['localizations'] = {}
        val_obj['localizations']['en'] = {
            'stringUnit': {
                'state': 'translated',
                'value': dictionary[key]
            }
        }

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Updated Localizable.xcstrings with all translations.")
